# version: "3.8"

services:
  agy-api:
    build: .
    ports:
      - "8686:8000"
    networks:
      - study
    environment:
      - AGY_API_KEY=sk-dummy
    volumes:
      - ./app:/app/app:ro
      - ~/.gemini:/root/.gemini
      - ~/.local/bin/agy:/usr/local/bin/agy:ro

networks:
  study:
    external: true
